### ISSUE TITLE
Request for also saving register data per session

### ISSUE THREAD

**Issue by EGmux** [jamescherti/easysession.el#16]
I heavily adopt registers to quickly move between windows in my sessions, but I've noticed that easysession.el won't save nor load them and currently I'm using the package [binky.el](https://github.com/liuyinz/binky.el) to mitigate this issue it offers `binky-restore` and `binky-save`, my problem is that is restricted to buffers and feels like an extra dependency considering that `consult-registers` pretty much offers the same and also framesets and files, I heavily use consult.

**would be possible to also save register data per session the same way framesets, windows and buffers/indirect buffers are saved?**

## Current way I'm doing it in .dir-locals.el
```lisp
(eval . (when (or (not (string= (easysession-get-current-session-name) "projectX")) (not (boundp 'initproject)))
                      (binky-restore "~/.emacs.d/binky/cache/projectX")))
          (eval . (setq initproject nil))
          (eval . (binky-save "~/.emacs.d/binky/cache/projectX"))
          (eval . (add-hook 'kill-emacs-hook #'(lambda () (binky-save "~/.emacs.d/binky/cache/projectX"))  nil t))
          (eval . (add-hook 'kill-emacs-hook #'(lambda () (makunbound 'initproject))  nil t))
```

**Comment by jamescherti** [comment]
Hello! 

Thank you for your enhancement suggestion.

Have you tried utilizing the savehist package to persist and restore register-alist?

**Comment by EGmux** [comment]
I've tried your suggestion, however `savehist` can only persist an alist of registers pointing to files, if any other type is present the register-alist is never persisted and  as mentioned  the proposed solution ideally should persist windows and frames.

My experience seems to align with this [reddit post:Persistent Registers](https://old.reddit.com/r/emacs/comments/c9dewr/persistent_registers/) as well. 

So I guess the ideal solution would be to contribute to the savehist package.I'll try to get a PR merged upstream.

**Comment by jamescherti** [comment]
Contributing a patch to savehist sounds like a good idea. It could be valuable to many users.
