### ISSUE TITLE
Daemon mode does not play well with this package

### ISSUE THREAD

**Issue by linwaytin** [jamescherti/easysession.el#18]
I've tried to use this package with daemon mode for a few hours, but it always shows strange behaviors, when using the automatic save mode. If I turn off the `easysession-save-mode`, and manually save the states, it seems to work, but this makes the workflow clumsy. 

I tried to use hooks to run `easysession-save` but failed. It seems this command has to be called interactively by the user.

**Comment by jamescherti** [comment]
Try using server-after-make-frame-hook instead of after-init-hook

**Comment by linwaytin** [comment]
For example, one thing I noticed is that when `easysession-save-interval` is small, like 5 seconds, it doesn't work.

**Comment by jamescherti** [comment]
How about manually running `easysession-save`, restarting Emacs, and then running `easysession-load`? Does it work?

**Comment by linwaytin** [comment]
Another issue is that when using `easysession-save-mode` with daemon, it seems to save the session when I restart the daemon (I use `systemctl`), and because usually there is no frame at that moment, it saves a empty session. 

I found manually using `easysession-save` and `easysession-load` is better. For example, I try
```
(add-hook 'after-save-hook #'easysession-save)
(add-hook 'mouse-leave-buffer-hook #'easysession-save)
(add-hook 'window-state-change-hook #'easysession-save)
```
and it seems to work well.

**Comment by linwaytin** [comment]
One more question related to the daemon mode. I usually have a main frame in the GUI mode, but sometimes I would like to open a terminal emacsclient quickly to edit something, just like using `vim`. They are belonging to the same session because of the daemon. Is it possible to make `easysession` govern only a frame and not the whole session? You mention visible buffers but I'm not sure if it is related.

**Comment by linwaytin** [comment]
Please ignore my last question. It is too different from the goal of this package, and I found in my use cases, the best way might be running 2 daemons for GUI and terminals. 

This is a great package. It indeed save and recover the indirect buffers I need.

**Comment by jamescherti** [comment]
I'm glad to hear that you find the package great. When I started using Emacs, I hadn't found any package that provided the same functionality as EasySession, which motivated me to develop it.

Try to always call `(easysession-load-including-geometry)` before `(easysession-save-mode)` to ensure that there is a session to save. You can also use the variable `easysession--current-session-loaded` to check if a session was loaded.

I also recommend you to try the following as an alternative to `easysession-save-mode`:
```lisp
(add-hook 'window-buffer-change-functions
          #'(lambda(&rest _)
              (easysession-save)))
```

Do you have any suggestions or paragraphs to add to the README.md regarding daemon mode?

**Comment by linwaytin** [comment]
Well, I would suggest having a link to this discussion, if you like. 

At this moment, I think the idea of session management does not play well with a server or daemon intrinsically. With an Emacs server, what is the end of a session? When closing a frame or ending the server? I believe this ambiguity is the essence of the problem, so even the built-in `desktop-mode` has issues with daemon-mode. The users of daemon-mode should know this.

Thanks a lot for your help and this nice package!

**Comment by jamescherti** [comment]
My pleasure, @linwaytin!

I also recommend taking a look at `easysession-add-load-handler` and `easysession-add-save-handler`. You could use them to create your own "easysession-NAME" package that handles additional types of buffers, in addition to the ones supported by EasySession (e.g., terminal buffers, and any other buffer specific to an Emacs package you are using).

**Comment by linwaytin** [comment]
I think I have the same issue as yours. For the daemon mode, currently I have my own function which checks the number of frames. The daemon mode has one default frame, so only when the number of frames is equal to 2 it runs `easysession-save`. But where to hook this function is a little tricky, because it seems that the number of frames is updated in real time.
